export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const VISION_REQUEST='VISION_REQUEST';
export const VISION_SUCCESS='VISION_SUCCESS';
export const VISION_FAILURE='VISION_FAILURE';

export const OCR_VISION_REQUEST='OCR_VISION_REQUEST';
export const OCR_VISION_SUCCESS='OCR_VISION_SUCCESS';
export const OCR_VISION_FAILURE='OCR_VISION_FAILURE';

export const HAND_VISION_REQUEST='HAND_VISION_REQUEST';
export const HAND_VISION_SUCCESS='HAND_VISION_SUCCESS';
export const HAND_VISION_FAILURE='HAND_VISION_FAILURE';

export const GET_IMAGE_URL = 'GET_IMAGE_URL';



export const IMAGE_REQUEST='IMAGE_REQUEST';
export const IMAGE_SUCCESS='IMAGE_SUCCESS';
export const IMAGE_FAILURE='IMAGE_FAILURE';


export const DROPZONE_REQUEST = 'DROPZONE_REQUEST';
export const DROPZONE_SUCCESS = 'DROPZONE_SUCCESS';
export const DROPZONE_ERROR = 'DROPZONE_ERROR';

export const SHOW_DROPZONE_PAGE = 'SHOW_DROPZONE_PAGE';
export const CLEAR_ALL = 'CLEAR_ALL';

export const SAVE_COSMOS_DB_REQUEST = 'SAVE_COSMOS_DB_REQUEST';
export const SAVE_COSMOS_DB_SUCCESS = 'SAVE_COSMOS_DB_SUCCESS';
export const SAVE_COSMOS_DB_FALIURE = 'SAVE_COSMOS_DB_FALIURE';

export const ON_SEARCH_REQUEST = 'ON_SEARCH_REQUEST';
export const ON_SEARCH_SUCCESS = 'ON_SEARCH_SUCCESS';
export const ON_SEARCH_FAILURE = 'ON_SEARCH_FAILURE';

export const ON_CLEAR_SEARCH = 'ON_CLEAR_SEARCH';

export const SHOW_VISION_DETAILS = 'SHOW_VISION_DETAILS';
export const HIDE_VISION_DETAILS = 'HIDE_VISION_DETAILS';